### ISSUE TITLE
pyispyb.app.extensions.auth.KeycloakDBGroupsAuthentication' has no attribute 'KeycloakDBGroupsAuthentication'

### ISSUE THREAD

**Issue by antolinos** [ispyb/py-ispyb#228]
The project in development with the predefined configuration will throw the following error:
```
AttributeError: module 'pyispyb.app.extensions.auth.KeycloakDBGroupsAuthentication' has no attribute 'KeycloakDBGroupsAuthentication'
```

The preconfigured auth.yml is:
```
- keycloak:
      ENABLED: true
      AUTH_MODULE: "pyispyb.app.extensions.auth.KeycloakDBGroupsAuthentication"
      AUTH_CLASS: "KeycloakDBGroupsAuthentication"

```
